human_factor_data = [
{'experience': 0.74,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.96,
  'resilience': 0.61,
  'worker': 'w_1'},
 {'experience': 0.97,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.63,
  'resilience': 0.24,
  'worker': 'w_1'},
 {'experience': 0.64,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.24,
  'resilience': 0.71,
  'worker': 'w_1'},
 {'experience': 0.06,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.14,
  'resilience': 0.76,
  'worker': 'w_1'},
 {'experience': 0.95,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.99,
  'resilience': 0.16,
  'worker': 'w_1'},
 {'experience': 0.08,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.49,
  'resilience': 0.23,
  'worker': 'w_1'},
 {'experience': 0.62,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.51,
  'resilience': 0.55,
  'worker': 'w_1'},
 {'experience': 0.97,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.71,
  'resilience': 0.93,
  'worker': 'w_1'},
 {'experience': 0.38,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.36,
  'resilience': 0.79,
  'worker': 'w_2'},
 {'experience': 0.04,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.45,
  'resilience': 0.7,
  'worker': 'w_2'},
 {'experience': 0.17,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.94,
  'resilience': 0.09,
  'worker': 'w_2'},
 {'experience': 0.98,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.49,
  'resilience': 0.7,
  'worker': 'w_2'},
 {'experience': 0.91,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.62,
  'resilience': 0.36,
  'worker': 'w_2'},
 {'experience': 0.22,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.29,
  'resilience': 0.69,
  'worker': 'w_2'},
 {'experience': 0.79,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.86,
  'resilience': 0.16,
  'worker': 'w_2'},
 {'experience': 0.8,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.33,
  'resilience': 0.72,
  'worker': 'w_2'},
 {'experience': 0.08,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.82,
  'resilience': 0.4,
  'worker': 'w_3'},
 {'experience': 0.62,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.01,
  'resilience': 0.98,
  'worker': 'w_3'},
 {'experience': 0.95,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.01,
  'resilience': 0.19,
  'worker': 'w_3'},
 {'experience': 0.45,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.11,
  'resilience': 0.64,
  'worker': 'w_3'},
 {'experience': 0.87,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.33,
  'resilience': 0.09,
  'worker': 'w_3'},
 {'experience': 0.88,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.29,
  'resilience': 0.19,
  'worker': 'w_3'},
 {'experience': 0.28,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.89,
  'resilience': 0.14,
  'worker': 'w_3'},
 {'experience': 0.76,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.38,
  'resilience': 0.24,
  'worker': 'w_3'},
 {'experience': 0.08,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.99,
  'resilience': 0.59,
  'worker': 'w_4'},
 {'experience': 0.35,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.88,
  'resilience': 0.23,
  'worker': 'w_4'},
 {'experience': 0.86,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.87,
  'resilience': 0.42,
  'worker': 'w_4'},
 {'experience': 0.88,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.91,
  'resilience': 0.79,
  'worker': 'w_4'},
 {'experience': 0.85,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.39,
  'resilience': 0.74,
  'worker': 'w_4'},
 {'experience': 0.33,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.49,
  'resilience': 0.87,
  'worker': 'w_4'},
 {'experience': 0.51,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.13,
  'resilience': 0.08,
  'worker': 'w_4'},
 {'experience': 0.6,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.26,
  'resilience': 0.26,
  'worker': 'w_4'},
 {'experience': 0.51,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.01,
  'resilience': 0.65,
  'worker': 'w_5'},
 {'experience': 0.31,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.43,
  'resilience': 0.84,
  'worker': 'w_5'},
 {'experience': 0.09,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.46,
  'resilience': 0.26,
  'worker': 'w_5'},
 {'experience': 0.73,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.9,
  'resilience': 0.15,
  'worker': 'w_5'},
 {'experience': 0.43,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.63,
  'resilience': 0.08,
  'worker': 'w_5'},
 {'experience': 0.04,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.01,
  'resilience': 0.6,
  'worker': 'w_5'},
 {'experience': 0.15,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.53,
  'resilience': 0.88,
  'worker': 'w_5'},
 {'experience': 0.7,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.79,
  'resilience': 0.19,
  'worker': 'w_5'},
 {'experience': 0.81,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.61,
  'resilience': 0.6,
  'worker': 'w_6'},
 {'experience': 0.76,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.69,
  'resilience': 0.17,
  'worker': 'w_6'},
 {'experience': 0.43,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.66,
  'resilience': 0.19,
  'worker': 'w_6'},
 {'experience': 0.03,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.74,
  'resilience': 0.48,
  'worker': 'w_6'},
 {'experience': 0.44,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.58,
  'resilience': 0.84,
  'worker': 'w_6'},
 {'experience': 0.43,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.61,
  'resilience': 0.19,
  'worker': 'w_6'},
 {'experience': 0.86,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.27,
  'resilience': 0.1,
  'worker': 'w_6'},
 {'experience': 0.92,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.65,
  'resilience': 0.84,
  'worker': 'w_6'},
 {'experience': 0.05,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.35,
  'resilience': 0.13,
  'worker': 'w_7'},
 {'experience': 0.36,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.95,
  'resilience': 0.62,
  'worker': 'w_7'},
 {'experience': 0.28,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.28,
  'resilience': 0.75,
  'worker': 'w_7'},
 {'experience': 1.0,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.75,
  'resilience': 0.44,
  'worker': 'w_7'},
 {'experience': 0.29,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.11,
  'resilience': 0.17,
  'worker': 'w_7'},
 {'experience': 0.21,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.91,
  'resilience': 0.54,
  'worker': 'w_7'},
 {'experience': 0.23,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.07,
  'resilience': 0.89,
  'worker': 'w_7'},
 {'experience': 0.89,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.86,
  'resilience': 0.89,
  'worker': 'w_7'},
 {'experience': 0.82,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.82,
  'resilience': 0.57,
  'worker': 'w_8'},
 {'experience': 0.51,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.85,
  'resilience': 0.69,
  'worker': 'w_8'},
 {'experience': 0.32,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.74,
  'resilience': 0.46,
  'worker': 'w_8'},
 {'experience': 0.85,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.97,
  'resilience': 0.85,
  'worker': 'w_8'},
 {'experience': 0.07,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.02,
  'resilience': 0.66,
  'worker': 'w_8'},
 {'experience': 0.51,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.4,
  'resilience': 0.05,
  'worker': 'w_8'},
 {'experience': 0.97,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.05,
  'resilience': 0.82,
  'worker': 'w_8'},
 {'experience': 0.57,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.34,
  'resilience': 0.17,
  'worker': 'w_8'},
 {'experience': 0.68,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.76,
  'resilience': 0.14,
  'worker': 'w_9'},
 {'experience': 0.59,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.89,
  'resilience': 0.49,
  'worker': 'w_9'},
 {'experience': 0.49,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.72,
  'resilience': 0.43,
  'worker': 'w_9'},
 {'experience': 0.49,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.09,
  'resilience': 0.08,
  'worker': 'w_9'},
 {'experience': 0.26,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.45,
  'resilience': 0.19,
  'worker': 'w_9'},
 {'experience': 0.35,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.65,
  'resilience': 0.1,
  'worker': 'w_9'},
 {'experience': 0.46,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.38,
  'resilience': 0.84,
  'worker': 'w_9'},
 {'experience': 0.67,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.04,
  'resilience': 0.53,
  'worker': 'w_9'},
 {'experience': 0.96,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.2,
  'resilience': 0.87,
  'worker': 'w_10'},
 {'experience': 0.48,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.46,
  'resilience': 0.82,
  'worker': 'w_10'},
 {'experience': 0.06,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.79,
  'resilience': 0.53,
  'worker': 'w_10'},
 {'experience': 0.69,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.75,
  'resilience': 0.49,
  'worker': 'w_10'},
 {'experience': 0.94,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.59,
  'resilience': 0.77,
  'worker': 'w_10'},
 {'experience': 0.77,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.37,
  'resilience': 0.1,
  'worker': 'w_10'},
 {'experience': 0.01,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.16,
  'resilience': 0.44,
  'worker': 'w_10'},
 {'experience': 0.56,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.26,
  'resilience': 0.11,
  'worker': 'w_10'},
 {'experience': 0.16,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.73,
  'resilience': 0.63,
  'worker': 'w_11'},
 {'experience': 0.3,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.76,
  'resilience': 0.48,
  'worker': 'w_11'},
 {'experience': 0.37,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.27,
  'resilience': 0.48,
  'worker': 'w_11'},
 {'experience': 0.2,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.96,
  'resilience': 0.83,
  'worker': 'w_11'},
 {'experience': 0.1,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.89,
  'resilience': 0.49,
  'worker': 'w_11'},
 {'experience': 0.76,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.39,
  'resilience': 0.24,
  'worker': 'w_11'},
 {'experience': 0.67,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.1,
  'resilience': 0.09,
  'worker': 'w_11'},
 {'experience': 0.24,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.81,
  'resilience': 0.42,
  'worker': 'w_11'},
 {'experience': 0.36,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.36,
  'resilience': 0.37,
  'worker': 'w_12'},
 {'experience': 0.23,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.58,
  'resilience': 0.01,
  'worker': 'w_12'},
 {'experience': 0.84,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.85,
  'resilience': 0.73,
  'worker': 'w_12'},
 {'experience': 0.37,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.98,
  'resilience': 0.26,
  'worker': 'w_12'},
 {'experience': 0.95,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 1.0,
  'resilience': 0.69,
  'worker': 'w_12'},
 {'experience': 0.21,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.56,
  'resilience': 0.19,
  'worker': 'w_12'},
 {'experience': 0.93,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.82,
  'resilience': 0.31,
  'worker': 'w_12'},
 {'experience': 0.37,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.95,
  'resilience': 0.83,
  'worker': 'w_12'},
 {'experience': 0.11,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.22,
  'resilience': 0.42,
  'worker': 'w_13'},
 {'experience': 0.6,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.06,
  'resilience': 0.55,
  'worker': 'w_13'},
 {'experience': 0.52,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.79,
  'resilience': 0.81,
  'worker': 'w_13'},
 {'experience': 0.71,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.87,
  'resilience': 0.13,
  'worker': 'w_13'},
 {'experience': 0.71,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.23,
  'resilience': 0.6,
  'worker': 'w_13'},
 {'experience': 0.11,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.38,
  'resilience': 0.08,
  'worker': 'w_13'},
 {'experience': 0.63,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.3,
  'resilience': 0.01,
  'worker': 'w_13'},
 {'experience': 0.4,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.36,
  'resilience': 0.15,
  'worker': 'w_13'},
 {'experience': 0.4,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.85,
  'resilience': 0.01,
  'worker': 'w_14'},
 {'experience': 0.75,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.53,
  'resilience': 0.99,
  'worker': 'w_14'},
 {'experience': 0.0,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.94,
  'resilience': 0.15,
  'worker': 'w_14'},
 {'experience': 0.7,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.35,
  'resilience': 0.18,
  'worker': 'w_14'},
 {'experience': 0.08,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.82,
  'resilience': 0.72,
  'worker': 'w_14'},
 {'experience': 0.09,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.8,
  'resilience': 0.42,
  'worker': 'w_14'},
 {'experience': 0.02,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.06,
  'resilience': 0.11,
  'worker': 'w_14'},
 {'experience': 0.18,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.35,
  'resilience': 0.38,
  'worker': 'w_14'},
 {'experience': 0.58,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.37,
  'resilience': 0.33,
  'worker': 'w_15'},
 {'experience': 0.65,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.79,
  'resilience': 0.69,
  'worker': 'w_15'},
 {'experience': 0.22,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.53,
  'resilience': 0.01,
  'worker': 'w_15'},
 {'experience': 0.22,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.38,
  'resilience': 0.15,
  'worker': 'w_15'},
 {'experience': 0.54,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.63,
  'resilience': 0.38,
  'worker': 'w_15'},
 {'experience': 0.57,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.73,
  'resilience': 0.55,
  'worker': 'w_15'},
 {'experience': 0.91,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.46,
  'resilience': 0.56,
  'worker': 'w_15'},
 {'experience': 0.22,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.37,
  'resilience': 0.61,
  'worker': 'w_15'},
 {'experience': 0.16,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.5,
  'resilience': 0.88,
  'worker': 'w_16'},
 {'experience': 0.84,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.81,
  'resilience': 0.01,
  'worker': 'w_16'},
 {'experience': 0.39,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.4,
  'resilience': 0.11,
  'worker': 'w_16'},
 {'experience': 0.37,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.59,
  'resilience': 0.53,
  'worker': 'w_16'},
 {'experience': 0.38,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.74,
  'resilience': 0.06,
  'worker': 'w_16'},
 {'experience': 0.56,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.46,
  'resilience': 0.12,
  'worker': 'w_16'},
 {'experience': 0.24,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.01,
  'resilience': 0.73,
  'worker': 'w_16'},
 {'experience': 0.21,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.23,
  'resilience': 0.14,
  'worker': 'w_16'},
 {'experience': 0.5,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.36,
  'resilience': 0.53,
  'worker': 'w_17'},
 {'experience': 0.96,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.46,
  'resilience': 0.79,
  'worker': 'w_17'},
 {'experience': 0.05,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.26,
  'resilience': 0.52,
  'worker': 'w_17'},
 {'experience': 0.71,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.22,
  'resilience': 0.05,
  'worker': 'w_17'},
 {'experience': 0.35,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.85,
  'resilience': 0.61,
  'worker': 'w_17'},
 {'experience': 0.54,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.88,
  'resilience': 0.4,
  'worker': 'w_17'},
 {'experience': 0.58,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.44,
  'resilience': 0.38,
  'worker': 'w_17'},
 {'experience': 0.68,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.1,
  'resilience': 0.56,
  'worker': 'w_17'},
 {'experience': 0.35,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.42,
  'resilience': 0.5,
  'worker': 'w_18'},
 {'experience': 0.75,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.75,
  'resilience': 0.17,
  'worker': 'w_18'},
 {'experience': 0.15,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.67,
  'resilience': 0.56,
  'worker': 'w_18'},
 {'experience': 0.39,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.96,
  'resilience': 0.4,
  'worker': 'w_18'},
 {'experience': 0.62,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.06,
  'resilience': 0.37,
  'worker': 'w_18'},
 {'experience': 0.1,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.19,
  'resilience': 0.64,
  'worker': 'w_18'},
 {'experience': 0.49,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.11,
  'resilience': 0.34,
  'worker': 'w_18'},
 {'experience': 0.49,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.87,
  'resilience': 0.21,
  'worker': 'w_18'},
 {'experience': 0.65,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.68,
  'resilience': 0.88,
  'worker': 'w_19'},
 {'experience': 0.2,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.21,
  'resilience': 0.26,
  'worker': 'w_19'},
 {'experience': 0.26,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.77,
  'resilience': 0.68,
  'worker': 'w_19'},
 {'experience': 0.38,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.83,
  'resilience': 0.88,
  'worker': 'w_19'},
 {'experience': 0.79,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.45,
  'resilience': 0.34,
  'worker': 'w_19'},
 {'experience': 0.17,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.93,
  'resilience': 0.18,
  'worker': 'w_19'},
 {'experience': 0.72,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.19,
  'resilience': 0.8,
  'worker': 'w_19'},
 {'experience': 0.21,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.97,
  'resilience': 0.12,
  'worker': 'w_19'},
 {'experience': 0.2,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.15,
  'resilience': 0.11,
  'worker': 'w_20'},
 {'experience': 0.71,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.69,
  'resilience': 0.25,
  'worker': 'w_20'},
 {'experience': 0.28,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.68,
  'resilience': 0.21,
  'worker': 'w_20'},
 {'experience': 0.78,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.99,
  'resilience': 0.96,
  'worker': 'w_20'},
 {'experience': 0.58,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.93,
  'resilience': 0.3,
  'worker': 'w_20'},
 {'experience': 0.0,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.6,
  'resilience': 0.8,
  'worker': 'w_20'},
 {'experience': 0.5,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.51,
  'resilience': 0.64,
  'worker': 'w_20'},
 {'experience': 0.19,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.1,
  'resilience': 0.29,
  'worker': 'w_20'},
 {'experience': 0.73,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.65,
  'resilience': 0.26,
  'worker': 'w_21'},
 {'experience': 0.03,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.31,
  'resilience': 0.69,
  'worker': 'w_21'},
 {'experience': 0.02,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.43,
  'resilience': 0.96,
  'worker': 'w_21'},
 {'experience': 0.53,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.26,
  'resilience': 0.6,
  'worker': 'w_21'},
 {'experience': 0.88,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.57,
  'resilience': 0.92,
  'worker': 'w_21'},
 {'experience': 0.52,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.76,
  'resilience': 0.36,
  'worker': 'w_21'},
 {'experience': 0.99,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.16,
  'resilience': 0.2,
  'worker': 'w_21'},
 {'experience': 0.48,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.05,
  'resilience': 0.56,
  'worker': 'w_21'},
 {'experience': 0.72,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.85,
  'resilience': 0.58,
  'worker': 'w_22'},
 {'experience': 0.77,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.71,
  'resilience': 0.12,
  'worker': 'w_22'},
 {'experience': 0.85,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.37,
  'resilience': 0.88,
  'worker': 'w_22'},
 {'experience': 0.79,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.41,
  'resilience': 0.44,
  'worker': 'w_22'},
 {'experience': 0.28,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.11,
  'resilience': 0.31,
  'worker': 'w_22'},
 {'experience': 0.14,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.28,
  'resilience': 0.9,
  'worker': 'w_22'},
 {'experience': 0.2,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.44,
  'resilience': 0.28,
  'worker': 'w_22'},
 {'experience': 0.69,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.64,
  'resilience': 0.42,
  'worker': 'w_22'},
 {'experience': 1.0,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.14,
  'resilience': 0.25,
  'worker': 'w_23'},
 {'experience': 0.72,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.41,
  'resilience': 0.51,
  'worker': 'w_23'},
 {'experience': 0.71,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.29,
  'resilience': 0.83,
  'worker': 'w_23'},
 {'experience': 0.39,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.76,
  'resilience': 0.37,
  'worker': 'w_23'},
 {'experience': 0.82,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.28,
  'resilience': 0.22,
  'worker': 'w_23'},
 {'experience': 0.3,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.56,
  'resilience': 0.46,
  'worker': 'w_23'},
 {'experience': 0.93,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.95,
  'resilience': 0.73,
  'worker': 'w_23'},
 {'experience': 0.22,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.58,
  'resilience': 0.04,
  'worker': 'w_23'},
 {'experience': 0.08,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.81,
  'resilience': 0.94,
  'worker': 'w_24'},
 {'experience': 0.24,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.78,
  'resilience': 0.69,
  'worker': 'w_24'},
 {'experience': 0.29,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.35,
  'resilience': 0.21,
  'worker': 'w_24'},
 {'experience': 0.42,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.68,
  'resilience': 0.25,
  'worker': 'w_24'},
 {'experience': 0.87,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.65,
  'resilience': 0.65,
  'worker': 'w_24'},
 {'experience': 0.01,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.74,
  'resilience': 0.5,
  'worker': 'w_24'},
 {'experience': 0.39,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.89,
  'resilience': 0.4,
  'worker': 'w_24'},
 {'experience': 0.72,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.83,
  'resilience': 0.43,
  'worker': 'w_24'},
 {'experience': 0.51,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.55,
  'resilience': 0.7,
  'worker': 'w_25'},
 {'experience': 0.58,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.56,
  'resilience': 0.58,
  'worker': 'w_25'},
 {'experience': 0.6,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.8,
  'resilience': 0.39,
  'worker': 'w_25'},
 {'experience': 0.02,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.72,
  'resilience': 0.91,
  'worker': 'w_25'},
 {'experience': 0.99,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.11,
  'resilience': 0.06,
  'worker': 'w_25'},
 {'experience': 0.6,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.76,
  'resilience': 0.43,
  'worker': 'w_25'},
 {'experience': 0.2,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.1,
  'resilience': 0.14,
  'worker': 'w_25'},
 {'experience': 0.35,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.97,
  'resilience': 0.46,
  'worker': 'w_25'},
 {'experience': 0.86,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.13,
  'resilience': 0.76,
  'worker': 'w_26'},
 {'experience': 0.52,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.27,
  'resilience': 0.67,
  'worker': 'w_26'},
 {'experience': 0.48,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.21,
  'resilience': 0.21,
  'worker': 'w_26'},
 {'experience': 0.93,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.54,
  'resilience': 0.44,
  'worker': 'w_26'},
 {'experience': 0.91,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.99,
  'resilience': 0.27,
  'worker': 'w_26'},
 {'experience': 0.88,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.5,
  'resilience': 0.82,
  'worker': 'w_26'},
 {'experience': 0.34,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.78,
  'resilience': 0.72,
  'worker': 'w_26'},
 {'experience': 0.92,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.93,
  'resilience': 0.79,
  'worker': 'w_26'},
 {'experience': 0.85,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.7,
  'resilience': 0.78,
  'worker': 'w_27'},
 {'experience': 0.04,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.27,
  'resilience': 0.2,
  'worker': 'w_27'},
 {'experience': 0.53,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.55,
  'resilience': 0.46,
  'worker': 'w_27'},
 {'experience': 0.66,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.35,
  'resilience': 0.94,
  'worker': 'w_27'},
 {'experience': 0.39,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.79,
  'resilience': 0.02,
  'worker': 'w_27'},
 {'experience': 0.66,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.29,
  'resilience': 0.14,
  'worker': 'w_27'},
 {'experience': 0.29,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.86,
  'resilience': 0.78,
  'worker': 'w_27'},
 {'experience': 0.67,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.4,
  'resilience': 0.1,
  'worker': 'w_27'},
 {'experience': 0.65,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.57,
  'resilience': 0.96,
  'worker': 'w_28'},
 {'experience': 0.43,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.24,
  'resilience': 0.3,
  'worker': 'w_28'},
 {'experience': 0.49,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.1,
  'resilience': 0.44,
  'worker': 'w_28'},
 {'experience': 0.93,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.88,
  'resilience': 0.87,
  'worker': 'w_28'},
 {'experience': 0.22,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.75,
  'resilience': 0.24,
  'worker': 'w_28'},
 {'experience': 0.72,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.21,
  'resilience': 0.61,
  'worker': 'w_28'},
 {'experience': 0.5,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.44,
  'resilience': 0.14,
  'worker': 'w_28'},
 {'experience': 0.35,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.13,
  'resilience': 0.3,
  'worker': 'w_28'},
 {'experience': 0.01,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.46,
  'resilience': 0.76,
  'worker': 'w_29'},
 {'experience': 0.91,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.83,
  'resilience': 0.84,
  'worker': 'w_29'},
 {'experience': 0.84,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.58,
  'resilience': 0.41,
  'worker': 'w_29'},
 {'experience': 0.53,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.67,
  'resilience': 0.85,
  'worker': 'w_29'},
 {'experience': 0.22,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.39,
  'resilience': 0.79,
  'worker': 'w_29'},
 {'experience': 0.55,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.63,
  'resilience': 0.83,
  'worker': 'w_29'},
 {'experience': 0.49,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.02,
  'resilience': 0.87,
  'worker': 'w_29'},
 {'experience': 0.45,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.51,
  'resilience': 0.28,
  'worker': 'w_29'},
 {'experience': 0.66,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.8,
  'resilience': 0.35,
  'worker': 'w_30'},
 {'experience': 0.56,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.45,
  'resilience': 0.33,
  'worker': 'w_30'},
 {'experience': 0.34,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.09,
  'resilience': 0.98,
  'worker': 'w_30'},
 {'experience': 0.52,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.74,
  'resilience': 0.39,
  'worker': 'w_30'},
 {'experience': 0.59,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.31,
  'resilience': 0.08,
  'worker': 'w_30'},
 {'experience': 0.22,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.46,
  'resilience': 0.51,
  'worker': 'w_30'},
 {'experience': 0.03,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.65,
  'resilience': 0.94,
  'worker': 'w_30'},
 {'experience': 0.2,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.55,
  'resilience': 0.85,
  'worker': 'w_30'},
 {'experience': 0.98,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.83,
  'resilience': 0.88,
  'worker': 'w_31'},
 {'experience': 0.36,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.22,
  'resilience': 0.95,
  'worker': 'w_31'},
 {'experience': 0.63,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.42,
  'resilience': 0.81,
  'worker': 'w_31'},
 {'experience': 0.27,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.82,
  'resilience': 0.36,
  'worker': 'w_31'},
 {'experience': 0.87,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.74,
  'resilience': 0.35,
  'worker': 'w_31'},
 {'experience': 0.0,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.05,
  'resilience': 0.94,
  'worker': 'w_31'},
 {'experience': 0.97,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.75,
  'resilience': 0.85,
  'worker': 'w_31'},
 {'experience': 0.44,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.93,
  'resilience': 0.3,
  'worker': 'w_31'},
 {'experience': 0.25,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.01,
  'resilience': 0.74,
  'worker': 'w_32'},
 {'experience': 0.43,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.7,
  'resilience': 0.96,
  'worker': 'w_32'},
 {'experience': 0.9,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.09,
  'resilience': 0.77,
  'worker': 'w_32'},
 {'experience': 0.09,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.36,
  'resilience': 0.39,
  'worker': 'w_32'},
 {'experience': 0.92,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.28,
  'resilience': 0.31,
  'worker': 'w_32'},
 {'experience': 0.36,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.73,
  'resilience': 0.69,
  'worker': 'w_32'},
 {'experience': 0.45,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.33,
  'resilience': 0.68,
  'worker': 'w_32'},
 {'experience': 0.21,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.26,
  'resilience': 0.8,
  'worker': 'w_32'},
 {'experience': 0.54,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.83,
  'resilience': 0.75,
  'worker': 'w_33'},
 {'experience': 0.07,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.54,
  'resilience': 0.46,
  'worker': 'w_33'},
 {'experience': 0.86,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.73,
  'resilience': 0.08,
  'worker': 'w_33'},
 {'experience': 0.47,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.69,
  'resilience': 0.0,
  'worker': 'w_33'},
 {'experience': 0.64,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.61,
  'resilience': 0.31,
  'worker': 'w_33'},
 {'experience': 0.58,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.03,
  'resilience': 0.61,
  'worker': 'w_33'},
 {'experience': 0.78,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.97,
  'resilience': 0.39,
  'worker': 'w_33'},
 {'experience': 0.58,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.48,
  'resilience': 0.15,
  'worker': 'w_33'},
 {'experience': 0.54,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.79,
  'resilience': 0.76,
  'worker': 'w_34'},
 {'experience': 0.52,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.69,
  'resilience': 0.05,
  'worker': 'w_34'},
 {'experience': 0.59,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.41,
  'resilience': 0.51,
  'worker': 'w_34'},
 {'experience': 0.5,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.17,
  'resilience': 0.16,
  'worker': 'w_34'},
 {'experience': 0.5,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.05,
  'resilience': 0.43,
  'worker': 'w_34'},
 {'experience': 0.29,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.66,
  'resilience': 0.58,
  'worker': 'w_34'},
 {'experience': 0.12,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.04,
  'resilience': 0.42,
  'worker': 'w_34'},
 {'experience': 0.8,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.69,
  'resilience': 0.87,
  'worker': 'w_34'},
 {'experience': 0.11,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.53,
  'resilience': 0.84,
  'worker': 'w_35'},
 {'experience': 0.43,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.36,
  'resilience': 0.74,
  'worker': 'w_35'},
 {'experience': 0.62,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.74,
  'resilience': 0.05,
  'worker': 'w_35'},
 {'experience': 0.38,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.5,
  'resilience': 0.45,
  'worker': 'w_35'},
 {'experience': 0.79,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.76,
  'resilience': 0.75,
  'worker': 'w_35'},
 {'experience': 0.32,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.75,
  'resilience': 0.17,
  'worker': 'w_35'},
 {'experience': 0.54,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.02,
  'resilience': 0.36,
  'worker': 'w_35'},
 {'experience': 0.43,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.89,
  'resilience': 0.77,
  'worker': 'w_35'},
 {'experience': 0.96,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.96,
  'resilience': 0.52,
  'worker': 'w_36'},
 {'experience': 0.61,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.14,
  'resilience': 0.63,
  'worker': 'w_36'},
 {'experience': 0.27,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.71,
  'resilience': 0.82,
  'worker': 'w_36'},
 {'experience': 0.9,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.25,
  'resilience': 0.81,
  'worker': 'w_36'},
 {'experience': 0.95,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.6,
  'resilience': 0.96,
  'worker': 'w_36'},
 {'experience': 0.71,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.19,
  'resilience': 0.49,
  'worker': 'w_36'},
 {'experience': 0.95,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.54,
  'resilience': 0.7,
  'worker': 'w_36'},
 {'experience': 0.64,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.35,
  'resilience': 0.19,
  'worker': 'w_36'},
 {'experience': 0.94,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.01,
  'resilience': 0.76,
  'worker': 'w_37'},
 {'experience': 0.02,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.62,
  'resilience': 0.96,
  'worker': 'w_37'},
 {'experience': 0.49,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.48,
  'resilience': 0.36,
  'worker': 'w_37'},
 {'experience': 0.53,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.24,
  'resilience': 0.4,
  'worker': 'w_37'},
 {'experience': 0.77,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.75,
  'resilience': 0.81,
  'worker': 'w_37'},
 {'experience': 0.66,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.68,
  'resilience': 0.64,
  'worker': 'w_37'},
 {'experience': 0.1,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.57,
  'resilience': 0.33,
  'worker': 'w_37'},
 {'experience': 0.92,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.87,
  'resilience': 0.74,
  'worker': 'w_37'},
 {'experience': 0.73,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.62,
  'resilience': 0.24,
  'worker': 'w_38'},
 {'experience': 0.02,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.88,
  'resilience': 0.47,
  'worker': 'w_38'},
 {'experience': 0.64,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.86,
  'resilience': 0.39,
  'worker': 'w_38'},
 {'experience': 0.55,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.2,
  'resilience': 0.0,
  'worker': 'w_38'},
 {'experience': 0.78,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.75,
  'resilience': 0.23,
  'worker': 'w_38'},
 {'experience': 0.72,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.35,
  'resilience': 0.69,
  'worker': 'w_38'},
 {'experience': 0.97,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.37,
  'resilience': 0.1,
  'worker': 'w_38'},
 {'experience': 0.39,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.62,
  'resilience': 0.68,
  'worker': 'w_38'},
 {'experience': 0.93,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.13,
  'resilience': 0.8,
  'worker': 'w_39'},
 {'experience': 0.15,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.57,
  'resilience': 0.77,
  'worker': 'w_39'},
 {'experience': 0.83,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.06,
  'resilience': 0.25,
  'worker': 'w_39'},
 {'experience': 0.07,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.52,
  'resilience': 0.39,
  'worker': 'w_39'},
 {'experience': 0.18,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.74,
  'resilience': 0.72,
  'worker': 'w_39'},
 {'experience': 0.79,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.53,
  'resilience': 0.93,
  'worker': 'w_39'},
 {'experience': 0.18,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.07,
  'resilience': 0.21,
  'worker': 'w_39'},
 {'experience': 0.34,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.35,
  'resilience': 0.57,
  'worker': 'w_39'},
 {'experience': 0.93,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.38,
  'resilience': 0.87,
  'worker': 'w_40'},
 {'experience': 0.57,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.46,
  'resilience': 0.36,
  'worker': 'w_40'},
 {'experience': 0.14,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.5,
  'resilience': 0.73,
  'worker': 'w_40'},
 {'experience': 0.08,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.94,
  'resilience': 0.36,
  'worker': 'w_40'},
 {'experience': 0.59,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.81,
  'resilience': 0.03,
  'worker': 'w_40'},
 {'experience': 0.47,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.39,
  'resilience': 0.6,
  'worker': 'w_40'},
 {'experience': 0.84,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.26,
  'resilience': 0.76,
  'worker': 'w_40'},
 {'experience': 0.19,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.68,
  'resilience': 0.68,
  'worker': 'w_40'},
 {'experience': 0.08,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.76,
  'resilience': 0.16,
  'worker': 'w_41'},
 {'experience': 0.39,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.18,
  'resilience': 0.31,
  'worker': 'w_41'},
 {'experience': 0.23,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.14,
  'resilience': 0.48,
  'worker': 'w_41'},
 {'experience': 0.58,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.67,
  'resilience': 0.18,
  'worker': 'w_41'},
 {'experience': 0.21,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.64,
  'resilience': 0.67,
  'worker': 'w_41'},
 {'experience': 0.25,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.83,
  'resilience': 0.16,
  'worker': 'w_41'},
 {'experience': 0.8,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.79,
  'resilience': 0.51,
  'worker': 'w_41'},
 {'experience': 0.92,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.37,
  'resilience': 0.12,
  'worker': 'w_41'},
 {'experience': 0.45,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.34,
  'resilience': 0.98,
  'worker': 'w_42'},
 {'experience': 0.01,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.67,
  'resilience': 0.92,
  'worker': 'w_42'},
 {'experience': 0.75,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.74,
  'resilience': 0.46,
  'worker': 'w_42'},
 {'experience': 0.28,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.9,
  'resilience': 0.69,
  'worker': 'w_42'},
 {'experience': 0.62,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.84,
  'resilience': 0.12,
  'worker': 'w_42'},
 {'experience': 0.31,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.34,
  'resilience': 0.7,
  'worker': 'w_42'},
 {'experience': 0.39,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.94,
  'resilience': 0.31,
  'worker': 'w_42'},
 {'experience': 0.6,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.56,
  'resilience': 0.65,
  'worker': 'w_42'},
 {'experience': 0.06,
  'geometry': 'Geometry 1',
  'medical_condition': 'true',
  'preference': 0.6,
  'resilience': 0.52,
  'worker': 'w_43'},
 {'experience': 0.93,
  'geometry': 'Geometry 2',
  'medical_condition': 'true',
  'preference': 0.19,
  'resilience': 0.59,
  'worker': 'w_43'},
 {'experience': 0.96,
  'geometry': 'Geometry 3',
  'medical_condition': 'true',
  'preference': 0.22,
  'resilience': 0.43,
  'worker': 'w_43'},
 {'experience': 0.13,
  'geometry': 'Geometry 4',
  'medical_condition': 'true',
  'preference': 0.4,
  'resilience': 0.12,
  'worker': 'w_43'},
 {'experience': 0.87,
  'geometry': 'Geometry 5',
  'medical_condition': 'true',
  'preference': 0.85,
  'resilience': 0.78,
  'worker': 'w_43'},
 {'experience': 0.19,
  'geometry': 'Geometry 6',
  'medical_condition': 'true',
  'preference': 0.43,
  'resilience': 0.61,
  'worker': 'w_43'},
 {'experience': 0.04,
  'geometry': 'Geometry 7',
  'medical_condition': 'true',
  'preference': 0.61,
  'resilience': 0.74,
  'worker': 'w_43'},
 {'experience': 0.31,
  'geometry': 'Geometry 8',
  'medical_condition': 'true',
  'preference': 0.99,
  'resilience': 0.53,
  'worker': 'w_43'}
]